# https://golangci-lint.run/usage/configuration/#config-file

linters:
  # The following linters require at least version 1.44 of golangci-lint.
  # https://golangci-lint.run/usage/linters/
  enable:
    - durationcheck
    - exportloopref
    - gci
    - gofmt
    - makezero
    - nakedret
    - predeclared
    - promlinter
    - tenv
    - bidichk
    - errchkjson

    # The following checks don't work with go1.18 (yet).
    # TODO: Re-enable them when https://github.com/golangci/golangci-lint/issues/2649
    # is resolved.
    #
    # - bodyclose
    # - contextcheck
    # - noctx
    # - rowserrcheck
    # - sqlclosecheck
