name: golang
on: push
jobs:
  lint:
    runs-on: buildjet-8vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/cache@v3
        # https://github.com/actions/cache/issues/720#issuecomment-1030412967
        timeout-minutes: 5
        continue-on-error: true
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      # https://github.com/golangci/golangci-lint-action
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: --timeout=5m
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run check_gotidy.sh
        run: |
          scripts/check_gotidy.sh

  test:
    runs-on: buildjet-8vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: airplanedevci
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/cache@v3
        # https://github.com/actions/cache/issues/720#issuecomment-1030412967
        timeout-minutes: 5
        continue-on-error: true
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: install fixture dependencies
        run: |
          cd pkg/deploy/discover/fixtures
          yarn
      - name: go test
        run: |
          go test -race -timeout=15m ./...
